apiVersion: v1
kind: Service
metadata:
  name: redisson-redis-cluster-management
  labels:
    app: redisson-redis-cluster
    type: management
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: management
  selector:
    app: redisson-redis-cluster